server:
  port: 8080
  servlet:
    context-path: /countryside
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: countryside
  datasource:
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/country
    platform: postgres
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
