server:
  port: 8080
  servlet:
    context-path: /countryside
spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: countryside
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.103:3306/countryside?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    platform: mysql
    schema: classpath:schema.sql
    data: classpath:init.sql
    initialization-mode: always
    sql-script-encoding: utf-8
    continue-on-error: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
